[package]
name = "ic-certified-map"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Merkleized map data structure."
homepage = "https://docs.rs/ic-certified-map"
documentation = "https://docs.rs/ic-certified-map"
readme = "README.md"
categories = [
    "data-structures",
    "cryptography",
    "cryptography::cryptocurrencies",
]
keywords = ["internet-computer", "types", "dfinity", "map"]
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]

[dependencies]
serde = "1"
serde_bytes = "0.11"
sha2 = "0.10"

[dev-dependencies]
hex = "0.4"
serde_cbor = "0.11"
ic-cdk = { path = "../../src/ic-cdk", version = "0.10" }
candid = "0.9"
serde = "1"
