[package]
name = "inter_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { path = "../../../../src/ic-cdk" }
ic-cdk-macros = { path = "../../../../src/ic-cdk-macros" }

[build-dependencies]
candid-build = { path = "../../../../src/candid-build" }
