[package]
name = "ic_cdk"
version = "0.1.0"
authors = ["Hans Larsen <hans@larsen.online>"]
edition = "2018"

[dependencies]
candid = "0.6.2"
cfg-if = "0.1.10"
ic-types = "0.1.1"
serde = "1.0.110"
wee_alloc = { version = "0.4.5" }
